---
title: "Untitled"
format: revealjs
editor: visual
---

### Abstract

Durante el año 2022 la LEC tuvo un gran impacto en los esports y se quiso saber cual jugador fue el mas predominante en la liga a nivel individual el cual se concluyo con los análisis de los datos que fue Upset jugador para el equipo de Fanatic Esports

### Introducción

Día a día cada vez hay más gente que se quiere dedicar al mundo de los "Esport" concepto dedicado a la competencia en videojuegos, con el objetivo de entretener a cierto publico de personas y con un beneficio lucrativo bastante importante, hablamos de miles de millones de dolares generados por los "Esports". Hoy en día uno de los juegos más conocido en el ámbito de la competición es el "League of legends".

El juego "League of legends" debe su fama al ser un juego de estrategia por equipos, de bajo rendimiento y ultimo y a la vez los mas importante es un juego gratuito, por lo que es accesible para algún grupo de amigos cualquiera sean sus computadoras, pero este no es motivo por el cual brilla tanto en los "Esports" sino que son sus jugadores. Un jugador de la LEC gana en promedio 15 millones de pesos chilenos mensuales y esto se debe a que son muy buenos en lo que hacen, osea jugando.

Dicho esto analizaremos a los jugadores de la liga LEC (League european championship),durante el año 2022 hasta la fecha 17-10, los cuales serán analizados y clasificados según su desempeño durante esta liga y ademas se hará un análisis de regresión lineal para ver cuales son las características dentro del juego que hacen a algún jugador destacar mas que otros.

### Datos

Se usaran datos obtenidos de la pagina Kaggle, de las cuales solo serán utilizadas las mencionadas en la sección "VARIABLES".

#### 
